# Generated by Django 5.0.4 on 2024-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('no_of_seats', models.IntegerField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=10)),
                ('availability', models.CharField(default='A', max_length=1)),
                ('available_seats', models.IntegerField(default=models.IntegerField())),
                ('no_of_rows', models.IntegerField(default=1)),
                ('no_of_columns', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField()),
                ('seat_row', models.IntegerField()),
                ('seat_col', models.IntegerField()),
                ('seat_status', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.IntegerField()),
                ('amt', models.FloatField()),
                ('bus_id', models.IntegerField()),
                ('seat_row', models.IntegerField()),
                ('seat_col', models.IntegerField()),
            ],
            options={
                'db_table': 'trans',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('mob_no', models.CharField(max_length=10)),
                ('type', models.CharField(default='C', max_length=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
